### PR TITLE
Allow Authy::API.register_user to take a :send_install_link_via_sms option

### PR DESCRIPTION
**Pull request by treznick**
Per the documentation in http://docs.authy.com/totp.html#totp-api

We are using the `authy-devise` gem for our production Rails app, and we want the option to not send users the install link via SMS when they register for authy.

Rather than fork both gems to pass in one flag to one request, we would love this to be merged!

We've attempted a spec, but given the existing structure of `Authy::API.register_user`, it doesn't appear that the client will fail when passed an option that it doesn't know how to deal with. Testing that the SMS sent doesn't have the link in question (ala an acceptance spec) seems outside of the scope of this PR.

Please let us know if there's anything else we can do to help! We love using this service and are happy to contribute toward its further open-source development.

Best,
Tom Reznick
Software Engineer
Continuity

cc @alexwilkinson

### CODE REVIEW

**Comment by treznick** [comment]
fixed a typo in the spec. Please let me know if this PR needs anything else.

**Comment by serargz** [comment]
Thanks for the PR @treznick, we'll shortly merge it to master.

**Comment by treznick** [comment]
Thanks! FWIW the documentation defaults the `:send_install_link_via_sms` option to `true`, but it looks like my PR sets this as false by default. I'll update this

**Comment by treznick** [comment]
@serargz Anything you all need on my end for this to get merged? Happy to help.

**Comment by treznick** [comment]
@serargz pinging again to see if this is ready to merge. Again, happy to make any changes you folks require. Feel free to reach out. Thanks!

**Comment by serargz** [comment]
@treznick I'm catching up with reviewing and approving pull requests, sorry for the long delay. Will get back to you soon.

**Comment by treznick** [comment]
no worries @serargz. Thanks for all the work maintaining this!

**Comment by serargz** [comment]
Thank you @treznick, PR merged.

**Comment by treznick** [comment]
Thanks!

**Pull request merged**
